import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // GitHub Pages serves the static export generated by the dedicated workflow.
  // The regular Cloudflare build remains server-rendered when STATIC_EXPORT is unset.
  ...(process.env.STATIC_EXPORT === "true"
    ? { output: "export" as const, assetPrefix: process.env.NEXT_PUBLIC_BASE_PATH ?? "/YomuDoom", images: { unoptimized: true } }
    : {}),
};

export default nextConfig;
